name: Check the protocol on pull request

on:
  pull_request:
    types: [synchronize, opened, reopened, edited]  #en zie https://github.com/actions/runner/issues/980
    branches:
     - main

jobs:
  run_if:
    if: startsWith(github.head_ref, 's[fioap]p-')
    runs-on: ubuntu-latest
    name: "check protocol"
    env:
      GITHUB_PAT: ${{ secrets.PAT }}
    steps:
      - name: Check protocol
        uses: ElsLommelen/actions/protocol_check@protocols
        with:
          GITHUB_PAT: ${{ secrets.PAT }}
