name: Update protocol (.zenodo.json and NEWS.md)

on:
  pull_request_review:
    types: [submitted]
    branches:
     - main

jobs:
  build:
    if: (github.event.review.state == 'approved') &&
      (startsWith(github.head_ref, 'sfp-')
      || startsWith(github.head_ref, 'sip-')
      || startsWith(github.head_ref, 'sop-')
      || startsWith(github.head_ref, 'sap-')
      || startsWith(github.head_ref, 'spp-'))
    runs-on: ubuntu-latest
    name: "update protocol"
    steps:
      - name: Update protocol
        uses: inbo/actions/protocol_update@master
        with:
          PAT: ${{ secrets.PAT }}
